export const mockCameras = [
  {
    id: '1',
    name: 'كاميرا المدخل الرئيسي',
    location: 'المدخل الرئيسي',
    status: 'online',
    streamUrl: 'https://placehold.co/1280x720/1f2937/10b981?text=ENTRANCE+CAMERA+01',
    lastFrame: 'https://placehold.co/1280x720/1f2937/10b981?text=ENTRANCE+CAMERA+01+%E2%80%A2+LIVE',
    alerts: [],
    createdAt: new Date('2024-01-15'),
    detectionCapabilities: ['fire', 'smoke', 'ppe'],
    isDetectionActive: true,
  },
  {
    id: '2',
    name: 'كاميرا المخزن',
    location: 'المخزن الرئيسي',
    status: 'online',
    streamUrl: 'https://placehold.co/1280x720/1f2937/3b82f6?text=WAREHOUSE+CAMERA+02',
    lastFrame: 'https://placehold.co/1280x720/1f2937/3b82f6?text=WAREHOUSE+CAMERA+02+%E2%80%A2+LIVE',
    alerts: [],
    createdAt: new Date('2024-01-16'),
    detectionCapabilities: ['fire', 'smoke'],
    isDetectionActive: true,
  },
  {
    id: '3',
    name: 'كاميرا منطقة الإنتاج',
    location: 'منطقة الإنتاج A',
    status: 'online',
    streamUrl: 'https://placehold.co/1280x720/1f2937/f59e0b?text=PRODUCTION+CAMERA+03',
    lastFrame: 'https://placehold.co/1280x720/1f2937/f59e0b?text=PRODUCTION+CAMERA+03+%E2%80%A2+LIVE',
    alerts: [],
    createdAt: new Date('2024-01-17'),
    detectionCapabilities: ['ppe'],
    isDetectionActive: true,
  },
  {
    id: '4',
    name: 'كاميرا الساحة الخارجية',
    location: 'الساحة الخارجية',
    status: 'offline',
    streamUrl: 'https://placehold.co/1280x720/374151/ef4444?text=OUTDOOR+CAMERA+04',
    lastFrame: 'https://placehold.co/1280x720/374151/ef4444?text=CAMERA+OFFLINE',
    alerts: [],
    createdAt: new Date('2024-01-18'),
    detectionCapabilities: ['fire', 'smoke'],
    isDetectionActive: false,
  },
  {
    id: '5',
    name: 'كاميرا غرفة التحكم',
    location: 'غرفة التحكم',
    status: 'online',
    streamUrl: 'https://placehold.co/1280x720/1f2937/8b5cf6?text=CONTROL+ROOM+05',
    lastFrame: 'https://placehold.co/1280x720/1f2937/8b5cf6?text=CONTROL+ROOM+05+%E2%80%A2+LIVE',
    alerts: [],
    createdAt: new Date('2024-01-19'),
    detectionCapabilities: ['fire', 'smoke', 'ppe'],
    isDetectionActive: true,
  },
  {
    id: '6',
    name: 'كاميرا موقف السيارات',
    location: 'موقف السيارات',
    status: 'online',
    streamUrl: 'https://placehold.co/1280x720/1f2937/06b6d4?text=PARKING+CAMERA+06',
    lastFrame: 'https://placehold.co/1280x720/1f2937/06b6d4?text=PARKING+CAMERA+06+%E2%80%A2+LIVE',
    alerts: [],
    createdAt: new Date('2024-01-20'),
    detectionCapabilities: ['fire', 'smoke'],
    isDetectionActive: true,
  },
];

export const mockSensors = [
  {
    id: '1',
    name: 'حساس الغاز - المخزن',
    type: 'gas',
    status: 'working',
    currentValue: 45,
    unit: 'PPM',
    minValue: 0,
    maxValue: 100,
    threshold: { min: 0, max: 80 },
    alerts: [],
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'حساس الحرارة - منطقة الإنتاج',
    type: 'temperature',
    status: 'working',
    currentValue: 28,
    unit: '°C',
    minValue: 15,
    maxValue: 50,
    threshold: { min: 18, max: 35 },
    alerts: [],
    createdAt: new Date('2024-01-16'),
  },
  {
    id: '3',
    name: 'حساس الحركة - المدخل الخلفي',
    type: 'motion',
    status: 'working',
    currentValue: 0,
    unit: '',
    minValue: 0,
    maxValue: 1,
    threshold: { min: 0, max: 0 },
    alerts: [],
    createdAt: new Date('2024-01-17'),
  },
  {
    id: '4',
    name: 'حساس الرطوبة - المخزن',
    type: 'humidity',
    status: 'working',
    currentValue: 62,
    unit: '%',
    minValue: 0,
    maxValue: 100,
    threshold: { min: 30, max: 70 },
    alerts: [],
    createdAt: new Date('2024-01-18'),
  },
  {
    id: '5',
    name: 'حساس الضغط - خط الأنابيب',
    type: 'pressure',
    status: 'error',
    currentValue: 0,
    unit: 'PSI',
    minValue: 0,
    maxValue: 200,
    threshold: { min: 20, max: 150 },
    alerts: [],
    createdAt: new Date('2024-01-19'),
  },
];

export const mockAlerts = [
  {
    id: '1',
    type: 'fire',
    sourceType: 'camera',
    sourceId: '1',
    sourceName: 'كاميرا المدخل الرئيسي',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    severity: 'critical',
    description: 'تم اكتشاف حريق في منطقة المدخل الرئيسي',
    resolved: true,
    resolvedBy: 'أحمد محمد',
    resolvedAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    imageUrl: 'https://placehold.co/400x300/dc2626/ffffff?text=Fire+Detected',
    detectionInfo: {
      detectionType: 'fire',
      confidence: 0.95
    }
  },
  {
    id: '2',
    type: 'smoke',
    sourceType: 'camera',
    sourceId: '2',
    sourceName: 'كاميرا المخزن',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    severity: 'high',
    description: 'تم اكتشاف دخان في المخزن الرئيسي',
    resolved: true,
    resolvedBy: 'سارة أحمد',
    resolvedAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    imageUrl: 'https://placehold.co/400x300/f59e0b/ffffff?text=Smoke+Detected',
    detectionInfo: {
      detectionType: 'smoke',
      confidence: 0.88
    }
  },
  {
    id: '3',
    type: 'ppe_violation',
    sourceType: 'camera',
    sourceId: '3',
    sourceName: 'كاميرا منطقة الإنتاج',
    timestamp: new Date(Date.now() - 30 * 60 * 1000),
    severity: 'medium',
    description: 'عامل بدون خوذة في منطقة الإنتاج',
    resolved: false,
    imageUrl: 'https://placehold.co/400x300/f59e0b/ffffff?text=No+Helmet',
    ppeViolationType: 'no_helmet',
    detectionInfo: {
      detectionType: 'ppe',
      confidence: 0.92,
      missingItems: ['helmet']
    }
  },
  {
    id: '4',
    type: 'gas',
    sourceType: 'sensor',
    sourceId: '1',
    sourceName: 'حساس الغاز - المخزن',
    timestamp: new Date(Date.now() - 10 * 60 * 60 * 1000),
    severity: 'critical',
    description: 'تسرب غاز خطير في المخزن - 95 PPM',
    resolved: true,
    resolvedBy: 'خالد عمر',
    resolvedAt: new Date(Date.now() - 9 * 60 * 60 * 1000),
  },
  {
    id: '5',
    type: 'temperature',
    sourceType: 'sensor',
    sourceId: '2',
    sourceName: 'حساس الحرارة - منطقة الإنتاج',
    timestamp: new Date(Date.now() - 45 * 60 * 1000),
    severity: 'high',
    description: 'درجة حرارة مرتفعة في منطقة الإنتاج - 42°C',
    resolved: false,
  },
  {
    id: '6',
    type: 'motion',
    sourceType: 'sensor',
    sourceId: '3',
    sourceName: 'حساس الحركة - المدخل الخلفي',
    timestamp: new Date(Date.now() - 15 * 60 * 1000),
    severity: 'medium',
    description: 'حركة غير مصرح بها في المدخل الخلفي',
    resolved: false,
  },
  {
    id: '7',
    type: 'ppe_violation',
    sourceType: 'camera',
    sourceId: '1',
    sourceName: 'كاميرا المدخل الرئيسي',
    timestamp: new Date(Date.now() - 20 * 60 * 1000),
    severity: 'high',
    description: 'عامل بدون سترة سلامة وقفازات',
    resolved: false,
    imageUrl: 'https://placehold.co/400x300/f59e0b/ffffff?text=PPE+Violation',
    ppeViolationType: 'no_vest',
    detectionInfo: {
      detectionType: 'ppe',
      confidence: 0.89,
      missingItems: ['vest', 'gloves']
    }
  },
];

export const mockTimelineEvents = [
  {
    id: '1',
    type: 'alert',
    timestamp: new Date(Date.now() - 20 * 60 * 1000),
    description: 'تنبيه: عامل بدون سترة سلامة وقفازات',
    icon: 'alert-triangle',
    severity: 'warning',
  },
  {
    id: '2',
    type: 'alert',
    timestamp: new Date(Date.now() - 30 * 60 * 1000),
    description: 'تنبيه: عامل بدون خوذة في منطقة الإنتاج',
    icon: 'alert-triangle',
    severity: 'warning',
  },
  {
    id: '3',
    type: 'alert',
    timestamp: new Date(Date.now() - 45 * 60 * 1000),
    description: 'تنبيه: درجة حرارة مرتفعة - 42°C',
    icon: 'thermometer',
    severity: 'error',
  },
  {
    id: '4',
    type: 'camera_offline',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    description: 'كاميرا الساحة الخارجية غير متصلة',
    icon: 'video-off',
    severity: 'warning',
  },
  {
    id: '5',
    type: 'alert',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    description: 'تم حل: تنبيه الدخان في المخزن',
    icon: 'check-circle',
    severity: 'info',
  },
];

export const mockAnalytics = {
  alertsPerDay: [
    { date: '2024-01-20', count: 5 },
    { date: '2024-01-21', count: 8 },
    { date: '2024-01-22', count: 3 },
    { date: '2024-01-23', count: 12 },
    { date: '2024-01-24', count: 7 },
    { date: '2024-01-25', count: 4 },
    { date: '2024-01-26', count: 9 },
  ],
  alertsByType: [
    { type: 'حريق', count: 15 },
    { type: 'دخان', count: 23 },
    { type: 'معدات السلامة', count: 45 },
    { type: 'غاز', count: 8 },
    { type: 'حرارة', count: 18 },
    { type: 'حركة', count: 12 },
  ],
  cameraStatus: {
    online: 5,
    offline: 1,
  },
  sensorActivity: [
    { name: 'حساس الغاز', alertCount: 8 },
    { name: 'حساس الحرارة', alertCount: 18 },
    { name: 'حساس الحركة', alertCount: 12 },
    { name: 'حساس الرطوبة', alertCount: 5 },
    { name: 'حساس الضغط', alertCount: 3 },
  ],
};
